version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "18:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: flake8
    versions:
    - 3.9.0
  - dependency-name: coverage
    versions:
    - "5.4"
  - dependency-name: isort
    versions:
    - 5.7.0
